fs = 1000;
t = 0:1 /fs:1;
f = 100;
x = sin(2*pi*f*t);
xf = fft(x);
n= length(x);
fcutoff = 50;
h = ones(n,1);
h(round(n*fcutoff/fs)+1:end)=0;
xf_filtered = xf .*h;
x_filtered = ifft(xf_filtered);
figure;
subplot(2,1,1);
plot(t,x);
title('Señal original');
xlabel('Tiempo(s)');
ylabel('Amplitud');
subplot(2,1,2);
plot(t,real(x_filtered));
title('Señal filtrada');
xlabel('Tiempo(s)');
ylabel('Amplitud');

